# Generated by Django 4.1.1 on 2022-09-30 12:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vessel_id', models.BigIntegerField(blank=True, null=True)),
                ('received_time_utc', models.DateField()),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
