# Generated by Django 4.1.1 on 2022-09-30 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0002_location_received_time_utc_idx_vessel_vessel_id_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vessel',
            options={'ordering': ['-vessel_id']},
        ),
    ]
