# Generated by Django 4.1.1 on 2022-10-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0003_alter_vessel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='geo_location',
            new_name='point',
        ),
    ]
