# Generated by Django 4.1.1 on 2022-10-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0004_rename_geo_location_location_point'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='location',
            name='received_time_utc_idx',
        ),
        migrations.RemoveIndex(
            model_name='vessel',
            name='vessel_id_idx',
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['received_time_utc', 'id'], name='received_time_utc_idx'),
        ),
        migrations.AddIndex(
            model_name='vessel',
            index=models.Index(fields=['vessel_id', 'id'], name='vessel_id_idx'),
        ),
    ]
