# Generated by Django 4.1.1 on 2022-10-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0005_remove_location_received_time_utc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
