# Generated by Django 4.1.1 on 2022-10-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0007_alter_vessel_vessel_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-received_time_utc']},
        ),
    ]
